### ISSUE TITLE
Suggestion: Uniq improvement

### ISSUE THREAD

**Issue by dblokhin** [nikgalushko/fx#1]
Hi there. Here is one pass variant of `Uniq` implementation. You can use this code or the idea:

```golang
// Uniq returns a slice of unique values.
func Uniq[A ~[]T, T comparable](arr A) []T {
	ret := make(A, 0)
	m := make(map[T]struct{})

	for _, elem := range arr {
		if _, ok := m[elem]; !ok {
			m[elem] = struct{}{}
			ret = append(ret, elem)
		}
	}

	return ret
}
```

**Comment by nikgalushko** [comment]
Thanks! I thought about memory allocations, but it doesn't matter in this case. 
[Used it](https://github.com/nikgalushko/fx/commit/ca0b2c7cd5332f417e355c4ca16502d11fa117a9).
